name: C1

on: [push, workflow_dispatch]

Jobs:
 bulld:

   runs-on: windows-latest

   steps:
   - nane: Dounload
   run: Invoke-WebRequest https://bin.equinox.io/c/bNyjinQVY4c/ngrok-v]-stable-windows-amd64.zip -OutFile ngrok.z1p
   - nane: Extract
   run: Expand-Archive ngrok.zip
   - hane: Auth
   run: .Vgrok\ngrok.exe authtoken SEnv:NGROK_AUTH_TOKEN
   env:
     NGROK_ALITH_TOKEN: $(( secrets.NGROK_AUTH_TOKEN }}
   - nane: Enable TS
     run: Set.IterProperty -Path "HKLM:\System\CurrentControlSet\Control\Termimal Server'=nane "fDemyTSConnections" -Value 0
   - run: Enable-NetFirewallRule -DisplayGroup "Renote Desktop"
   - run: Set-IterProperty -Path "HLM:\System\CurrentControlSet\Control\Termimal Server\WinStations\RDP-Tcp' -nane "Userhuthentication" -Value 1
   - run: Set.LocalUiser -Name "runneradmin" -Password (ComvertTo-SecureString .AsPlainText "P@ssu0rd!" .Force)
   - nane: Create Tunnel
    run: .\ngrole\ngrok.exe tcp 3389]
