name: C1

on: [push, workflow_dispatch]

jobs:
  build:

       runs-on: windows-latest

       steps:
       - name: Download
         run: Inveke-hlebRequest https://bin.equinax.io/c/blyjimQW&c/ngrok-v3-stable-windows-and64.zip -OutFile ngrok.zip
       - hame: Extract
         run: Expaed-Archive ngrok.zlp
       - hame: Auth
         run: .\ngrok\ngrok.exe authtoken SEnv:NGROK_NUTH_TOKEN
         env:
           NGROK_AUTH_TOKEN: $(( secrets.NGROK_AUTH_TOKEN }}
       - name: Enable TS
         run: Set-IterProperty -Path "HLM:\Systen\CurrentComtrolSet\Control\Termimal Server'-nane "+DenyTSConnections" -Value @
       - run: Enable-NetFirewallRule -DisplayGroup "Renote Desktop"
       - run: Set-IterProperty -Path "H(LM:\Systen\CurrentComtrolSet\Control\Termimal Server\WinStations\ROP-Tcp' -name "UserAuthentication" -Value 1
       - run: Set-LocalUser -Nane "runneradmin" -Password (ComvertTo-SecureString -AsPlainText "P@ssw@rd!" -Force)
       - name: Create Tunnel
         run: .Vngrok\ngrok.exe tcp 3389
